version: '3.9'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    tmpfs:
      - /data

  app:
    image: axmz/distrilock:latest
    build:
      context: .
      dockerfile: Dockerfile.distrilock
    env_file:
      - .env
    depends_on:
      - redis
      - verifier
    deploy:
      replicas: 5
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - .git/
        - action: rebuild
          path: go.mod
        - action: rebuild
          path: go.sum
        - action: rebuild
          path: ./cmd/distrilock/main.go
        - action: rebuild
          path: .env
        - action: rebuild
          path: ./cmd/verifier/main.go

  verifier:
    image: axmz/verifier:latest
    build:
      context: .
      dockerfile: Dockerfile.verifier
    env_file:
      - .env
    depends_on:
      - redis
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - .git/
        - action: rebuild
          path: go.mod
        - action: rebuild
          path: go.sum
        - action: rebuild
          path: ./cmd/verifier/main.go
