
apiVersion: apps/v1
kind: Deployment
metadata:
  name: verifier
  namespace: distrilock-redis-cluster
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "2"
spec:
  replicas: {{ .Values.verifier.replicaCount }}
  selector:
    matchLabels:
      app: verifier
  template:
    metadata:
      labels:
        app: verifier
    spec:
      initContainers:
        - name: wait-for-redis-cluster
          image: redis:7-alpine
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for Redis cluster to be ready..."
              until redis-cli -h redis-cluster ping; do
                echo "Waiting for Redis cluster..."
                sleep 5
              done
              echo "Redis cluster is ready!"
      containers:
        - name: verifier
          image: axmz/verifier:cluster
          ports:
            - containerPort: 50051
          envFrom:
            - configMapRef:
                name: distrilock-env
---
apiVersion: v1
kind: Service
metadata:
  name: verifier
  namespace: distrilock-redis-cluster
spec:
  ports:
    - port: 50051
  selector:
    app: verifier
 